[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_BASE_URL = "https://ulster-delt.netlify.app"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs" 